package life.mingming.community.mapper;

import java.util.List;
import life.mingming.community.model.User;
import life.mingming.community.model.UserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GITHUB_USER
     *
     * @mbg.generated Wed Sep 07 10:56:57 CST 2022
     */
    int updateByPrimaryKey(User row);
}